alterações

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -41,14 +41,16 @@ jobs:
           chmod +x geckodriver
           sudo cp geckodriver /snap/bin/geckodriver
           sudo mv geckodriver /usr/local/bin/
-#          echo "FIREFOX_BINARY=$FIREFOX_PATH" >> $GITHUB_ENV
+          echo "FIREFOX_BINARY=$FIREFOX_PATH" >> $GITHUB_ENV
 
       - name: Run Robot Framework tests
         env:
           WORK_TOKEN: ${{ secrets.GIT_TOKEN }}
           TZ: America/Sao_Paulo
         run: |
-           robot --variable BROWSER:firefox --variable HEADLESS:True --outputdir results ProjetoRobotCICD/Tests/
+          if ! robot --variable BROWSER:firefox --variable HEADLESS:True --outputdir results ProjetoRobotCICD/Tests/; then
+            echo "Robot Framework tests failed. Rerunning failed tests..."
+          fi
 #          if ! robot --outputdir results --exclude skip ProjetoRobotCICD/Tests/; then
 #            echo "Robot Framework tests failed. Rerunning failed tests..."
 #            if [ -f results/output.xml ]; then
